### ISSUE TITLE
0.3.1 Breaking Changes?

### ISSUE THREAD

**Issue by colinhemphill** [rnosov/react-reveal#5] opened 2017-09-29 17:59 UTC
Were there breaking changes between 0.3.0 and 0.3.1? I upgraded to 0.4 today, and my components that include `react-reveal` will no longer run. I tried downgrading to 0.3.0 and it worked, but 0.3.1 and later give me the same result:

```
bundle.js:5732 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Home`.
```

The `Home` component in this instance runs just fine if I remove any Reveal instances, which are built according to the docs:

```
<Reveal ssr className="row" effect="animated fadeInUp"></Reveal>
```

**Comment by rnosov** [comment] 2017-09-29 20:37
Hi Colin, there shouldn't be any breaking changes from 0.3.0 to 0.3.1. 
I've added  named exports like `Zoom` and `Fade` to `react-reveal` in addition to default `Reveal` component in 0.3.1. The idea being is that you can just write `<Fade up className="row" ssr>content</Fade>` without importing `animate.css` in your css. But the old way should still work fine.

It looks to me that you're getting entire `exports` object into `Reveal` variable instead of just default export for some reason. Do you mind sharing how exactly you import `Reveal` component into your project ( exact import statement ), your module bundler ( webpack etc )and  also the output of `console.log(Reveal)` just to see what kind of object you are getting instead? In particular, look for `default` property which could be a Reveal component we're after.

I can't reproduce this issue so let me know the results as others might experience the same problem.

**Comment by rnosov** [comment] 2017-09-29 21:40
Okay, I think i figured the issue.  According to this [Stackoverflow answer](https://stackoverflow.com/a/33705077) 
> Babel 5 used to have a compatibility hack for export default: if a module contained only one export, and it was a default export, it was assigned to module.exports.

 I've just check the transpiled output of 0.3.0 and there was this hack in there. Later versions don't have it ( because of named exports )  so you're getting problems. So I think it is the same case here. Their solution is to use something like:
```jsx
var Reveal = require('./react-reveal').default;
```
in ES5 code to get the default export in a non hacky way. I would suggest to re-factor your code to use named exports like `Fade`. Something like this in ES5:
```jsx
var Fade = require('./react-reveal').Fade;
```
I'm going to close this issue as named exports are quite useful and this is not something related to `react-reveal` in particular.

**Closed by rnosov** 2017-09-29 21:40 UTC
