### ISSUE TITLE
Not working properly on Safari 11 or IE11

### ISSUE THREAD

**Issue by luskin** [rnosov/react-reveal#24] opened 2018-04-05 22:08 UTC
I have implemented this and it is working on Chrome and Firefox however sometimes it doesn't work on Safari or IE11. After inspecting I have discovered that after scrolling past a Fade element, even after sitting on it for a while and scrolling back and forth, the css for `.react-reveal` remains `opacity: 0`.

<img width="301" alt="screen shot 2018-04-05 at 3 07 32 pm" src="https://user-images.githubusercontent.com/5702322/38394388-193d99dc-38e3-11e8-8026-81e329768cf5.png">

I have an onReveal callback that successfully works on Chrome as well and this does not get fired on Safari or IE11 either. Here is my implementation:

<img width="708" alt="screen shot 2018-04-05 at 3 08 08 pm" src="https://user-images.githubusercontent.com/5702322/38394405-2daa9dde-38e3-11e8-9ca2-129b3a3f1b26.png">

`
    <Fade right onReveal={this.handleOnReveal}>
      <img src={Images.TruckLiftgate} alt="truck_with_liftgate" />
    </Fade>
`

When visiting the react-reveal website on safari all the examples work so this must be an implementation problem that is specific to safari/ie. Any help would be greatly appreciated, love this package but we will have to remove it from our upcoming site if we can't get it working.

**Comment by csyo** [comment] 2018-04-11 07:48
I have the same problem on Safari 11 too.

**Comment by scorchiowned** [comment] 2018-04-11 10:57
Same here

**Comment by mongru** [comment] 2018-04-11 11:28
Same issue. Safari 11 as well. Anyone had any success in fixing this?

**Comment by rnosov** [comment] 2018-05-16 14:07
Guys, I can't reproduce this issue. If someone is willing to post the a sample project with this issue I can have a look. One thing you can do is explicitly set width and height of the image as it would greatly simplify browser workload and could be a source of this problem. `react-reveal` also needs relatively unmessed stylesheets to be able to show/hide images. I'm closing this issue for now but feel free to post sample projects.

**Closed by rnosov** 2018-05-16 14:07 UTC

**Comment by alexdanilowicz** [comment] 2018-06-21 20:12
Hello was there ever a solution for this? Having the same issue. Don't use transition nor overflow explicitly in my css, but fade is not loading properly in Safari 10.12. Works beautifully on Chrome.

**Comment by rnosov** [comment] 2018-06-24 01:17
@alexdanilowicz Can you create a sample project ( with source ) with this issue so I can have a look? 
I'm having a problem reproducing it as it works fine for me on Safari

**Comment by alexdanilowicz** [comment] 2018-06-24 21:04
My apologies I was testing on Safari 10.12. Upgrading to Safari 11 did the trick. I imagine there is no solution for users with an older version of the browser? Thanks so much for your response.

**Comment by djflorio** [comment] 2018-06-29 16:16
I was having this issue as well, but it turned out to be because my parent App component was set to absolute positioning. I had done that so I could conditionally set `overflow: hidden` on the App to prevent scrolling while a modal was open. I nixed that idea and react-reveal began working on Safari again.

**Comment by xbreid** [comment] 2018-09-03 01:10
Has anyone found a work around for this? I'm using `overflow: hidden`, but I need it for the design of the site I'm building.

**Comment by Nandez89** [comment] 2018-11-19 22:41
This issue is still happening, some elements stop showing because the opacity is stuck in 0 on safari.

**Comment by franck212** [comment] 2018-11-20 15:19
I have had this pb with react-reveal and impossible for me to solve it. So I used [CCSTransition](https://reactcommunity.org/react-transition-group/css-transition) from react-transition-group and now it works.

**Comment by vanya2h** [comment] 2019-01-12 18:10
Same here. Safari opacity 0

**Comment by RSpencerFink** [comment] 2019-07-02 20:33
+1

**Comment by n0umankhan** [comment] 2019-08-07 13:26
+1

**Comment by n0umankhan** [comment] 2019-08-09 07:25
+1

**Comment by n0umankhan** [comment] 2019-08-09 07:57
@rnosov shall we reopen this issue again as many of us are still facing this, Steps to reproduce this issue,

Create a scrollable div and apply Fade, Zoom to inner elements.

This problem is related to scrollable container as i guess you take window as scrollable container while it should be ideal if we can define our own scrollableContainer where we can pass id or class of scrollable div. Please have a look on this issue again.

**Comment by malekjaroslav** [comment] 2019-08-19 14:07
It happens to me as well, only when using `unmountOnExit={true} mountOnEnter={true}`

**Comment by PolGuixe** [comment] 2019-09-20 14:33
Has anyone managed to make it work on IE11.

The react-reveal website isn't working on IE11.

**Comment by KimPaow** [comment] 2019-09-22 19:35
Issues when using display table-cell as well.

**Comment by joe2son** [comment] 2019-10-02 16:00
Pretty weird that this is closed, dude! Categorically doesn't work on IE/Edge or Safari. Going to have to jump over to something else.

**Comment by jpgutti** [comment] 2019-10-22 16:30
Have someone found a solution or a workaround?

**Comment by VivianChan1998** [comment] 2019-11-20 12:12
I used `<Fade top duration={delayDuration} distance="20px"  spy appear>` in all components a list, and my original problem was that the components' opacity randomly end at 0, around0.5, and sometimes 1(which it should end), if I focus on another page and comes back, everything gets normal.
I used the solution mentioned above, **removing all `transition`, `transition-duration` properties** in the child components, and things worked out.

**Comment by PolGuixe** [comment] 2020-02-14 15:42
Has anyone found an alternative to React-reveal that works on IE 11?
